# Generated by Django 2.2 on 2021-04-18 01:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('phone', models.CharField(max_length=20)),
                ('roles', models.TextField()),
                ('about', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=256)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Profile')),
            ],
            options={
                'verbose_name': 'sociallink',
                'verbose_name_plural': 'sociallinks',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Profile')),
                ('technology', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Technology')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('slug', models.SlugField(unique=True)),
                ('technologies', models.ManyToManyField(to='projects.Technology')),
            ],
        ),
    ]
