# Generated by Django 2.2 on 2021-04-18 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Technology'),
        ),
    ]
